name: Bliss
favicon: null
layout_spectrum: 0.53556
typography_spectrum: 0.47778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b3b3b3'
    - '#484848'
    - '#8e8e8e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 2fe668bc-03bb-4120-98a1-ec676390acd4
    url: null
